### PR TITLE
Homework22

### PR DESCRIPTION
**Pull request by timurk8**

### CODE REVIEW

**Comment by timurk8** [comment]
Homework22RenamePlaylist

**Comment by Berichicko** [comment]
You should use encapsulation of non-static and non-final fields.

If a variable is used only by other methods of that class, it should be declared as private.

I recommend:  make all the locators and WebElements private, because private keyword in java allows most restrictive access to variables and methods and offer strongest form of Encapsulation. 

For example

    ```
    private By shuffleBtnLocator = By.cssSelector(".btn-shuffle-all");
    private By firstSongLocator = By.cssSelector(".play");

```
   @FindBy(css = "img.avatar")
    private WebElement avatar
```


I recommend: make the variables protected, because protected access gives the subclass a chance to use the helper method or variable, while preventing a nonrelated class from trying to use it.

```
    protected Actions actions;
    protected WebDriverWait wait;
    protected WebDriver driver;
```

**Comment by Berichicko** [comment]
image

HINT

Clean_Test

**Comment by Berichicko** [comment]
Please finish the homework!You got this problem, please correct it. 

image

**Pull request merged**
